---
blank_issues_enabled: false
contact_links:
  - name: Malcolm Issues @ DHS CISA
    url: https://github.com/cisagov/malcolm/issues?q=is%3Aissue+is%3Aopen+-label%3Atraining
    about: Issue and project tracking is managed in DHS CISA's fork upstream.
