# Copyright (c) 2025 Battelle Energy Alliance, LLC.  All rights reserved.

logging.metrics.enabled: false

filebeat.inputs:
- type: log
  paths:
    - ${BEAT_LOG_PATTERN:/home/sensor/zeek_logs/*.log}
    - ${BEAT_STATIC_LOG_PATTERN:/home/sensor/zeek_logs/static/*.log}
  symlinks: true
  fields_under_root: true
  tags: ["_filebeat_zeek_hedgehog_live"]
  compression_level: 0
  exclude_lines: ['^\s*#']
  scan_frequency: ${BEAT_SCAN_FREQUENCY:10s}
  clean_inactive: ${BEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${BEAT_IGNORE_OLDER:120m}
  close_inactive: ${BEAT_CLOSE_INACTIVE:90m}
  close_renamed: ${BEAT_CLOSE_RENAMED:true}
  close_removed: ${BEAT_CLOSE_REMOVED:true}
  close_eof: ${BEAT_CLOSE_EOF:false}
  clean_renamed: ${BEAT_CLEAN_RENAMED:true}
  clean_removed: ${BEAT_CLEAN_REMOVED:true}

- type: log
  paths:
    - ${BEAT_SURICATA_LOG_PATTERN:/home/sensor/zeek_logs/suricata/eve*.json}
  symlinks: true
  fields_under_root: true
  tags: ["_filebeat_suricata_hedgehog_live"]
  compression_level: 0
  scan_frequency: ${BEAT_SCAN_FREQUENCY:10s}
  clean_inactive: ${BEAT_CLEAN_INACTIVE:180m}
  ignore_older: ${BEAT_IGNORE_OLDER:120m}
  close_inactive: ${BEAT_CLOSE_INACTIVE:90m}
  close_renamed: ${BEAT_CLOSE_RENAMED:true}
  close_removed: ${BEAT_CLOSE_REMOVED:true}
  close_eof: ${BEAT_CLOSE_EOF:false}
  clean_renamed: ${BEAT_CLEAN_RENAMED:true}
  clean_removed: ${BEAT_CLEAN_REMOVED:true}

output.logstash:
  hosts: ["${BEAT_LS_HOST}:${BEAT_LS_PORT}"]
  ssl.enabled: ${BEAT_LS_SSL:false}
  ssl.certificate_authorities: ["${BEAT_LS_SSL_CA_CRT}"]
  ssl.certificate: "${BEAT_LS_SSL_CLIENT_CRT}"
  ssl.key: "${BEAT_LS_SSL_CLIENT_KEY}"
  ssl.supported_protocols: "TLSv1.2"
  ssl.verification_mode: "${BEAT_LS_SSL_VERIFY}"
