---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeek-live-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: zeek-live-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: zeek-live-deployment
    spec:
      containers:
      - name: zeek-live-container
        image: ghcr.io/idaholab/malcolm/zeek:25.02.0
        imagePullPolicy: Always
        stdin: false
        tty: true
        securityContext:
          capabilities:
            add:
              # NET_ADMIN and NET_RAW - to turn on promiscuous mode and capture raw packets
              - NET_ADMIN
              - NET_RAW
              # SYS_NICE - to set process nice values, real-time scheduling policies, I/O scheduling
              - SYS_NICE
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: zeek-env
          - secretRef:
              name: zeek-secret-env
          - configMapRef:
              name: zeek-live-env
          - configMapRef:
              name: pcap-capture-env
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: zeek-live-var-local-catrust-volume
          - mountPath: "/zeek/extract_files"
            name: zeek-live-zeek-volume
            subPath: "extract_files"
          - mountPath: "/zeek/upload"
            name: zeek-live-zeek-volume
            subPath: "upload"
          - mountPath: "/opt/zeek/share/zeek/site/custom/configmap"
            name: zeek-live-custom-volume
          - mountPath: "/opt/zeek/share/zeek/site/intel-preseed/configmap"
            name: zeek-live-intel-preseed-volume
          - mountPath: "/opt/zeek/share/zeek/site/intel"
            name: zeek-live-intel-volume
            subPath: "zeek/intel"
      initContainers:
      - name: zeek-live-dirinit-container
        image: ghcr.io/idaholab/malcolm/dirinit:25.02.0
        imagePullPolicy: Always
        stdin: false
        tty: true
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/config:zeek/intel/Mandiant,zeek/intel/MISP,zeek/intel/STIX;/data/zeek-logs:current,extract_files/preserved,extract_files/quarantine,live,processed,upload"
        volumeMounts:
          - name: zeek-live-intel-volume
            mountPath: "/data/config"
          - name: zeek-live-zeek-volume
            mountPath: "/data/zeek-logs"
      volumes:
        - name: zeek-live-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: zeek-live-zeek-volume
          persistentVolumeClaim:
            claimName: zeek-claim
        - name: zeek-live-custom-volume
          configMap:
            name: zeek-custom
        - name: zeek-live-intel-preseed-volume
          configMap:
            name: zeek-intel-preseed
        - name: zeek-live-intel-volume
          persistentVolumeClaim:
            claimName: config-claim
