# Generated by Django 4.1.7 on 2023-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malcolm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareinstallation',
            name='CPE',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='ModelNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='PackageURL',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='SBOM_URL',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='SKU',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='SerialNumber',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='URI',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='softwareinstallation',
            name='URI_Namespace',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='Name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='PatchNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='softwareinstallation',
            name='Version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductIdentificationHelpers',
        ),
    ]
